### ISSUE TITLE
Better notation for renamings

### ISSUE THREAD

**Issue by andrejbauer** [Chaaaos/formaltt#8]
If renamings are almost always written as `_⇒r_ {θ = θ} Γ Δ` then we should actually use a different notation, for example, `renaming θ Γ Δ` or `Renaming θ Γ Δ`. (Do we have a consistent strategy for which words to capitalize?)

Regarding `t [ ρ ]r`, this sort of notation is good for *contravariant* action, such as substitution. Renaming is covariant, so we should have a notation that puts `ρ` on the left of `t`. Maybe `[ ρ ]r t` or something like that.

**Comment by cilinder** [comment]
There was a refactoring of the code, which involved the definitions of renamings and substitutions.
Among the changes is that the action of a renaming is now from the left, which is in line with its covariant nature.
We also changed the definition of substitution so that it now acts covariantly. Its action was adjusted accordingly.
The definition of a substitution now also explicitly considers the MetaContext.
The strategy of which words to capitalize is not as of now set in stone. There are however ad-hoc naming conventions for renamings, substitutions and instantiations.
